name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Initialize Terraform
        run: terraform init
        # working-directory: ./ec2

      - name: Plan Terraform
        run: terraform plan
        # working-directory: ./ec2

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./ec2
